### ISSUE TITLE
Update metadata (`home`, etc.)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/py2app-feedstock#24]
The Bitbucket link [included here]( https://github.com/conda-forge/py2app-feedstock/blob/24dffcd61239ca1ebe4e445d64e16f82f0dd4e85/recipe/meta.yaml#L54 ) is dead. Would be good to update to [the new `home`]( https://github.com/ronaldoussoren/py2app ).

Same story with [`dev_url`]( https://github.com/conda-forge/py2app-feedstock/blob/24dffcd61239ca1ebe4e445d64e16f82f0dd4e85/recipe/meta.yaml#L65 ).

Also the `license_file` is now packaged. So [the vendored one]( https://github.com/conda-forge/py2app-feedstock/blob/24dffcd61239ca1ebe4e445d64e16f82f0dd4e85/recipe/LICENSE.txt ) can be dropped.

**Comment by bkpoon** [comment]
Thanks!
